package frontend;

/**
* frontend/DFRSFrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/ramata/workspace/FRONTEND/frontend.idl
* vendredi 2 décembre 2016 13 h 39 EST
*/

public final class DFRSFrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public frontend.DFRSFrontEnd value = null;

  public DFRSFrontEndHolder ()
  {
  }

  public DFRSFrontEndHolder (frontend.DFRSFrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = frontend.DFRSFrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    frontend.DFRSFrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return frontend.DFRSFrontEndHelper.type ();
  }

}
