package frontend;


/**
* frontend/DFRSFrontEndPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/ramata/workspace/FRONTEND/frontend.idl
* vendredi 2 décembre 2016 13 h 39 EST
*/

public abstract class DFRSFrontEndPOA extends org.omg.PortableServer.Servant
 implements frontend.DFRSFrontEndOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("transferReservation", new java.lang.Integer (0));
    _methods.put ("bookFlight", new java.lang.Integer (1));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (2));
    _methods.put ("editFlightRecord", new java.lang.Integer (3));
    _methods.put ("allFlights", new java.lang.Integer (4));
    _methods.put ("allBookings", new java.lang.Integer (5));
    _methods.put ("shutDown", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // frontend/DFRSFrontEnd/transferReservation
       {
         String passengerID = in.read_string ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         String $result = null;
         $result = this.transferReservation (passengerID, currentCity, otherCity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // frontend/DFRSFrontEnd/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String phoneNumber = in.read_string ();
         String address = in.read_string ();
         String destination = in.read_string ();
         String dateOfFlight = in.read_string ();
         String flightClass = in.read_string ();
         String $result = null;
         $result = this.bookFlight (firstName, lastName, phoneNumber, address, destination, dateOfFlight, flightClass);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // frontend/DFRSFrontEnd/getBookedFlightCount
       {
         int recordType = in.read_long ();
         String $result = null;
         $result = this.getBookedFlightCount (recordType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // frontend/DFRSFrontEnd/editFlightRecord
       {
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editFlightRecord (recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // frontend/DFRSFrontEnd/allFlights
       {
         String $result = null;
         $result = this.allFlights ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // frontend/DFRSFrontEnd/allBookings
       {
         String $result = null;
         $result = this.allBookings ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // frontend/DFRSFrontEnd/shutDown
       {
         this.shutDown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:frontend/DFRSFrontEnd:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DFRSFrontEnd _this() 
  {
    return DFRSFrontEndHelper.narrow(
    super._this_object());
  }

  public DFRSFrontEnd _this(org.omg.CORBA.ORB orb) 
  {
    return DFRSFrontEndHelper.narrow(
    super._this_object(orb));
  }


} // class DFRSFrontEndPOA
