package frontend;


/**
* frontend/DFRSFrontEndHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/ramata/workspace/FRONTEND/frontend.idl
* vendredi 2 décembre 2016 13 h 39 EST
*/

abstract public class DFRSFrontEndHelper
{
  private static String  _id = "IDL:frontend/DFRSFrontEnd:1.0";

  public static void insert (org.omg.CORBA.Any a, frontend.DFRSFrontEnd that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static frontend.DFRSFrontEnd extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (frontend.DFRSFrontEndHelper.id (), "DFRSFrontEnd");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static frontend.DFRSFrontEnd read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DFRSFrontEndStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, frontend.DFRSFrontEnd value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static frontend.DFRSFrontEnd narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof frontend.DFRSFrontEnd)
      return (frontend.DFRSFrontEnd)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      frontend._DFRSFrontEndStub stub = new frontend._DFRSFrontEndStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static frontend.DFRSFrontEnd unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof frontend.DFRSFrontEnd)
      return (frontend.DFRSFrontEnd)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      frontend._DFRSFrontEndStub stub = new frontend._DFRSFrontEndStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
