package frontend;


/**
* frontend/DFRSFrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/ramata/workspace/FRONTEND/frontend.idl
* vendredi 2 décembre 2016 13 h 39 EST
*/

public interface DFRSFrontEnd extends DFRSFrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DFRSFrontEnd
